export const APPLICATION_NAME = 'Catering.App'

export const SERVICE_TYPE_TO_ORDER_TYPE = {
  delivery: 'Delivery',
  pickup: 'TakeAway',
}

export const PAYMENT_OPTIONS = {
  PAY_FULL: 'PAY_FULL',
  PAY_DEPOSIT: 'PAY_DEPOSIT',
  PAY_LATER: 'PAY_LATER',
}

export const ORDER_STATUSES = {
  DRAFT: 'DRAFT',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  IN_PREP: 'IN_PREP',
  READY: 'READY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
}

export const PAYMENT_STATUSES = {
  UNPAID: 'UNPAID',
  DEPOSIT_PENDING: 'DEPOSIT_PENDING',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
}

export const REVIEW_FLAG_TYPES = {
  LEAD_TIME_BREACH: 'LEAD_TIME_BREACH',
  SLOT_SATURATED: 'SLOT_SATURATED',
  DELIVERY_OUTSIDE_ZONE: 'DELIVERY_OUTSIDE_ZONE',
  MIN_ORDER_NOT_MET: 'MIN_ORDER_NOT_MET',
  GUEST_COUNT_ABOVE_AUTO_CONFIRM: 'GUEST_COUNT_ABOVE_AUTO_CONFIRM',
  TOTAL_ABOVE_AUTO_CONFIRM: 'TOTAL_ABOVE_AUTO_CONFIRM',
  SPECIAL_REQUEST_REVIEW: 'SPECIAL_REQUEST_REVIEW',
  PACKAGE_UNAVAILABLE: 'PACKAGE_UNAVAILABLE',
  BLACKOUT_DATE: 'BLACKOUT_DATE',
}

export const TERMINAL_ORDER_STATUSES = new Set([
  ORDER_STATUSES.COMPLETED,
  ORDER_STATUSES.CANCELLED,
  ORDER_STATUSES.REJECTED,
])
