const businessRefId = '42d4a7e1-661a-4e72-a822-27112f8e0128'
const primaryRestaurantRefId = '89e21218-a8c2-46f4-ab92-9746b26ccd4b'

export const seedData = {
  businessRefId,
  categories: [
    { refId: 'cat_steakburger', name: 'Steakburger Platters', displayOrder: 0 },
    { refId: 'cat_sandwich', name: 'Melt & Sandwich Trays', displayOrder: 1 },
    { refId: 'cat_shakes', name: 'Shake Packages', displayOrder: 2 },
    { refId: 'cat_sides', name: 'Fries & Sides', displayOrder: 3 },
    { refId: 'cat_beverages', name: 'Beverage Packages', displayOrder: 4 },
  ],
  stores: [
    {
      refId: primaryRestaurantRefId,
      businessRefId,
      name: 'Nova Catering San Ramon',
      aliasName: 'San Ramon Catering Hub',
      address: '2410 San Ramon Valley Blvd Ste 150, San Ramon, CA 94583',
      phoneNumber: '(925) 555-1100',
      timeZone: 'America/Los_Angeles',
      geoLocation: { latitude: 37.7799, longitude: -121.978 },
      storeStatus: { status: 'open', isStoreClosed: false, isOpenForScheduledOrders: true, storeInfoMessage: 'OPEN NOW' },
      listingConfig: { allowedOrderTypes: ['Delivery', 'TakeAway'] },
      config: {
        currency: 'USD',
        leadTimeHours: 18,
        modifyCutoffHours: 12,
        minimumOrderAmount: 125,
        deliveryFee: 25,
        serviceFeeRate: 0.05,
        taxRate: 0.0825,
        depositPercentage: 0.3,
        slotCapacityGuests: 250,
        autoConfirmMaxGuests: 120,
        autoConfirmMaxTotal: 750,
        blackoutDates: ['2026-12-25', '2026-01-01'],
      },
      deliveryZones: [
        {
          refId: 'zone_san_ramon_local',
          label: 'San Ramon / Dublin',
          matchTerms: ['san ramon', 'dublin', '94583', '94582', '94568'],
          surcharge: 0,
        },
        {
          refId: 'zone_danville',
          label: 'Danville Extended',
          matchTerms: ['danville', '94506', '94526'],
          surcharge: 10,
        },
      ],
    },
    {
      refId: 'rest_walnut_creek',
      businessRefId,
      name: 'Nova Catering Walnut Creek',
      aliasName: 'Walnut Creek Catering Studio',
      address: '1344 North Main St, Walnut Creek, CA 94596',
      phoneNumber: '(925) 555-2200',
      timeZone: 'America/Los_Angeles',
      geoLocation: { latitude: 37.9063, longitude: -122.0651 },
      storeStatus: { status: 'open', isStoreClosed: false, isOpenForScheduledOrders: true, storeInfoMessage: 'OPEN NOW' },
      listingConfig: { allowedOrderTypes: ['Delivery', 'TakeAway'] },
      config: {
        currency: 'USD',
        leadTimeHours: 24,
        modifyCutoffHours: 16,
        minimumOrderAmount: 175,
        deliveryFee: 30,
        serviceFeeRate: 0.06,
        taxRate: 0.0875,
        depositPercentage: 0.35,
        slotCapacityGuests: 320,
        autoConfirmMaxGuests: 150,
        autoConfirmMaxTotal: 900,
        blackoutDates: ['2026-11-26'],
      },
      deliveryZones: [
        {
          refId: 'zone_wc_local',
          label: 'Walnut Creek / Pleasant Hill',
          matchTerms: ['walnut creek', 'pleasant hill', '94596', '94597', '94523'],
          surcharge: 0,
        },
        {
          refId: 'zone_concord',
          label: 'Concord Extended',
          matchTerms: ['concord', '94518', '94519', '94520', '94521'],
          surcharge: 12,
        },
      ],
    },
  ],
  packages: [
    {
      refId: 'pkg_original_double_platter',
      categoryRefId: 'cat_steakburger',
      menuItemRefId: 'menu_original_double_slider',
      name: 'Original Double Steakburger Platter',
      description: 'Twenty classic steakburger sliders with cheese, lettuce, tomato, and pickle.',
      price: 49.99,
      serves: 10,
      unit: 'tray (20 pcs)',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_original_double_slider', categoryRefId: 'cat_steakburger', quantity: 20 },
      ],
    },
    {
      refId: 'pkg_frisco_melt_tray',
      categoryRefId: 'cat_steakburger',
      menuItemRefId: 'menu_frisco_melt_slider',
      name: 'Frisco Melt Platter',
      description: 'Twenty premium Frisco melt sliders on sourdough.',
      price: 54.99,
      serves: 10,
      unit: 'tray (20 pcs)',
      imageUrl: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_frisco_melt_slider', categoryRefId: 'cat_steakburger', quantity: 20 },
      ],
    },
    {
      refId: 'pkg_western_bbq_platter',
      categoryRefId: 'cat_steakburger',
      menuItemRefId: 'menu_western_bbq_slider',
      name: 'Western BBQ Steakburger Platter',
      description: 'Thirty bold BBQ steakburger sliders with onion rings and bacon.',
      price: 64.99,
      serves: 15,
      unit: 'tray (30 pcs)',
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_western_bbq_slider', categoryRefId: 'cat_steakburger', quantity: 30 },
      ],
    },
    {
      refId: 'pkg_patty_melt_tray',
      categoryRefId: 'cat_sandwich',
      menuItemRefId: 'menu_patty_melt_half',
      name: 'Patty Melt Tray',
      description: 'Twenty patty melt halves on grilled rye with Swiss and onions.',
      price: 44.99,
      serves: 10,
      unit: 'tray (20 halves)',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_patty_melt_half', categoryRefId: 'cat_sandwich', quantity: 20 },
      ],
    },
    {
      refId: 'pkg_mixed_sandwich_platter',
      categoryRefId: 'cat_sandwich',
      menuItemRefId: 'menu_mixed_sandwich_platter',
      name: 'Mixed Sandwich Platter',
      description: 'Assortment of patty melts, grilled chicken, and BLT halves.',
      price: 54.99,
      serves: 15,
      unit: 'tray (30 halves)',
      imageUrl: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_mixed_sandwich_platter', categoryRefId: 'cat_sandwich', quantity: 30 },
      ],
    },
    {
      refId: 'pkg_assorted_shake_pack',
      categoryRefId: 'cat_shakes',
      menuItemRefId: 'menu_assorted_shake_pack',
      name: 'Assorted Shake Party Pack',
      description: 'Fifteen assorted hand-dipped shakes for dessert or beverage service.',
      price: 59.99,
      serves: 15,
      unit: 'pack (15 cups)',
      imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_assorted_shake_pack', categoryRefId: 'cat_shakes', quantity: 15 },
      ],
    },
    {
      refId: 'pkg_cheese_fries_party_tray',
      categoryRefId: 'cat_sides',
      menuItemRefId: 'menu_cheese_fries_tray',
      name: 'Cheese Fries Party Tray',
      description: 'Large tray of signature fries with warm cheese sauce.',
      price: 29.99,
      serves: 10,
      unit: 'tray',
      imageUrl: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_cheese_fries_tray', categoryRefId: 'cat_sides', quantity: 1 },
      ],
    },
    {
      refId: 'pkg_onion_ring_tower',
      categoryRefId: 'cat_sides',
      menuItemRefId: 'menu_onion_ring_tower',
      name: 'Onion Ring Tower',
      description: 'Sixty golden onion rings with ranch and BBQ dips.',
      price: 24.99,
      serves: 10,
      unit: 'tray (60 pcs)',
      imageUrl: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_onion_ring_tower', categoryRefId: 'cat_sides', quantity: 60 },
      ],
    },
    {
      refId: 'pkg_coke_package',
      categoryRefId: 'cat_beverages',
      menuItemRefId: 'menu_coke_case',
      name: 'Coca-Cola Beverage Package',
      description: 'Assorted Coca-Cola products chilled and ready to serve.',
      price: 24.99,
      serves: 12,
      unit: 'case (24 cans)',
      imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_coke_case', categoryRefId: 'cat_beverages', quantity: 24 },
      ],
    },
    {
      refId: 'pkg_lemonade_dispenser',
      categoryRefId: 'cat_beverages',
      menuItemRefId: 'menu_lemonade_dispenser',
      name: 'Lemonade Dispenser',
      description: 'Two-gallon self-serve lemonade dispenser with cups and ice.',
      price: 19.99,
      serves: 15,
      unit: 'dispenser (2 gal)',
      imageUrl: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop',
      isPublished: true,
      availabilitySettings: ['Online', 'Catering'],
      packageItems: [
        { menuItemRefId: 'menu_lemonade_dispenser', categoryRefId: 'cat_beverages', quantity: 1 },
      ],
    },
  ],
}
